export const applicationFormUrl = "https://forms.gle/omAC3Mu6itU1YSyJ8";

export const courses=[
 ["Domestic Data Entry Operator","360 hours","English","IT/ITES","9th to 10th","₹25,000","Available"],["Sewing Machine Operator · AMH/Q0301","—","—","Apparel","—","—","—"],["Tailoring Course for Beginners","14:40 hours","English","Textiles","Any","₹25,000","Not available"],["Field Technician – Computers & Peripherals","10:20 hours","English","Electronics","—","₹5,000","Available"],["Advance Diploma in Computer Application","360 hours","English","IT/ITES","10th to Graduate","₹25,000","Available"],["CorelDRAW 2022 Essential Training","200 hours","English","IT/ITES","Any","₹25,000","Not available"],["AutoCAD Essentials for Civil Engineer","31:00 hours","English","IT/ITES","Graduate","₹5,000","Not available"],["Web Design & Development","3:39 hours","English","IT/ITES","Graduate","₹25,000","Not available"],["Mobile Repairing","On enquiry","—","—","—","—","—"],["Automotive Service Technician","On enquiry","—","—","—","—","—"],["Introduction to Automobiles","On enquiry","—","—","—","—","—"],["Solar Panel Installation Technician","On enquiry","—","—","—","—","—"]
] as const;
export const placements=[
 ["Wiring Harness Assemble Operator","Yazaki India Pvt. Ltd.","Bangalore","Apprenticeship","150","₹17,000–₹18,500"],["Assembly Line Operator","Tata Electronics Pvt. Ltd.","Bangalore","Full time","100","₹19,618–₹24,327"],["Electronic Hardware Design Engineer","Satyam Software Solutions Pvt. Ltd.","Noida","Full time","50","₹16,000–₹25,000"],["Assembly / Testing Operator","Hon Hai Technology Group (Foxconn)","Bangalore","Full time","300","₹17,000–₹25,000"],["Laptop Assembly Technician","Dixcon Technology Pedget","Bangalore","Full time","200","₹16,500–₹19,200"],["Wiring DRE-2 Technician","Stellantis Engineering India Pvt. Ltd.","Bangalore","Full time","90","₹17,600–₹26,200"]
] as const;
export const schemes={
 "pmgdisha":{name:"PMGDISHA",year:"2020–21",trainees:"300",projects:"1",agency:"CSC Governance Services India Ltd",coverage:"Odisha · Ganjam",summary:"Digital literacy for rural citizens, including marginalised communities and differently-abled persons.",detail:"Pradhan Mantri Gramin Digital Saksharta Abhiyaan (PMGDISHA) aimed to make six crore people in rural India digitally literate, reaching around 40% of rural households through one eligible member from each household.",highlights:["Operate computers and digital access devices such as tablets and smartphones.","Use email, internet search, government services and digital payments.","Bridge the digital divide for rural communities, including SC, ST, minority, BPL, women and differently-abled learners."]},
 "pmkvy-rpl":{name:"PMKVY / RPL",year:"2020–21",trainees:"50",projects:"1",agency:"CSC Governance Services India Ltd",coverage:"Odisha · Ganjam",summary:"Recognition of Prior Learning for people with existing skills.",detail:"Recognition of Prior Learning (RPL) is a PMKVY skill-certification component that enables Indian youth with prior learning experience or skills to be assessed and certified, helping them secure a better livelihood. It particularly supports people working in unregulated sectors.",highlights:["Register existing skills for industry-relevant assessment.","Receive certification for prior learning and work experience.","Build a stronger path to livelihood opportunities."]},
 "nsdc-paid-segment":{name:"NSDC Paid Segment",year:"2020–26",trainees:"600",projects:"1",agency:"IT&ITS SSC",coverage:"Odisha · Ganjam",summary:"Skill development through a public-private partnership model.",detail:"National Skill Development Corporation (NSDC) is a not-for-profit public-private partnership organisation that supports private-sector skill-development initiatives. It functions under the Ministry of Skill Development & Entrepreneurship.",highlights:["Supports quality vocational skill-development initiatives.","Encourages private-sector operational and financial participation.","Works under the Ministry of Skill Development & Entrepreneurship."]},
 "sipda":{name:"SIPDA",year:"2021–22",trainees:"150 PwDs",projects:"1",agency:"DEPWD",coverage:"Odisha · Ganjam",summary:"Barrier-free access and skill support for Persons with Disabilities.",detail:"The SIPDA scheme under SCPwD supports a barrier-free environment for persons with disabilities in schools, colleges, training institutions, offices, public buildings, recreational areas and health facilities.",highlights:["Access features including ramps, rails, lifts and adapted toilets.","Braille signage, auditory signals, tactile flooring and accessible crossings.","Improved participation for wheelchair users and people with visual impairments."]},
 "csr-projects":{name:"CSR Projects",year:"2021–22",trainees:"67 PwDs",projects:"1",agency:"EFFICOR",coverage:"Odisha · Ganjam",summary:"Accenture Learning Exchange professional, digital and employability modules.",detail:"Accenture Learning Exchange, delivered under Leonard Cheshire, combines professional and employability development with digital learning modules for PwD learners.",highlights:["Adaptability, communication, customer service, problem solving and teamwork.","Career planning, job-search strategies, digital literacy and financial literacy.","Computer courses including email, internet, Microsoft Office, social media and typing."]},
 "cemca-ofc":{name:"CEMCA OFC Women’s & PWD Course",year:"2021–22",trainees:"50 PwDs + 100 women",projects:"1",agency:"ELECTRONIC SSC",coverage:"Odisha · Ganjam",summary:"Online certification in Optical Fiber Splicer training.",detail:"CEMCA collaborated with CSC e-Governance Services India Limited to deliver online skill-development training and certification in Optical Fiber Splicer courses through CSC Skill Training Centres approved by SCPwD and NSKFDC.",highlights:["Training and certification for Divyangjan learners and women.","Optical Fiber Splicer course delivered through CSC Skill Training Centres.","Partnership intended to raise awareness among VLEs, operators, stakeholders and beneficiaries."]},
 "future-workspace":{name:"Future Workspace Skills Training",year:"2022–23",trainees:"956 PwDs",projects:"1",agency:"AIF",coverage:"Odisha · Ganjam",summary:"Career mentoring and market-aligned training for PwD students.",detail:"The American India Foundation project provides skills development for PwD students through career mentoring, online skilling platforms and market-aligned employability training, while encouraging an entrepreneurial mindset.",highlights:["Career mentoring and online-skilling support.","Market-aligned employability training for PwD students.","Completion certification from NSDC and the University of Mumbai."]},
 "osda":{name:"OSDA Placement Link Training",year:"2023–26",trainees:"500 + 30 PwDs",projects:"1",agency:"OSDA",coverage:"Odisha · Ganjam & Rayagada",summary:"Placement-linked skill training for inclusive growth.",detail:"The OSDA placement-linked training programme supports Odisha's commitment to inclusive growth through skill development, connecting modern technologies with traditional sectors for a dynamic and sustainable future.",highlights:["Placement-linked skill development.","Inclusive opportunities for general candidates and PwD learners.","Delivery across Ganjam and Rayagada districts."]},
 "nabskill":{name:"NABARD / NABSKILL",year:"2023–24 & 2025–26",trainees:"60 + 60 SHI candidates",projects:"2",agency:"NABARD",coverage:"Odisha · Ganjam",summary:"Off-farm sector stakeholder and initiative interface.",detail:"NABARD is India's apex development financial institution, with a mandate to support rural prosperity through credit and non-credit initiatives in agriculture, cottage and village industries, handicrafts and small-scale industries. NABSKILL is its digital interface for recording stakeholders and off-farm initiatives.",highlights:["Captures Project Implementing Agencies and NABARD off-farm initiatives.","Supports rural development across agriculture, village industries, handicrafts and small-scale industries.","Two projects delivered across 2023–24 and 2025–26."]},
 "pmdaksh":{name:"PMDAKSH",year:"2025–26",trainees:"60 SHI candidates",projects:"1",agency:"DEPWD",coverage:"Odisha · Ganjam",summary:"Training for PwDs towards wage or self-employment.",detail:"The Department of Empowerment of Persons with Disabilities implements the National Action Plan for Skill Development of Persons with Disabilities (NAP-SDP), launched in March 2015 under SIPDA. Training is delivered through empanelled government and non-government Training Partners.",highlights:["Build self-reliance and productive participation for persons with disabilities.","Support gainful wage or self-employment.","Help learners integrate with mainstream society."]}
} as const;
export const schemeList=Object.entries(schemes);
export const team=[["Bibhuti Bhusan Swain","President"],["Bikash Kumar Swain","Secretary"],["Madhusmita Pradhan","Treasurer"],["Bikash Chandra Muni","State Head"],["Kesab Kumar Dakua","Placements Officer"],["Goutam Pradhan","Principal of Bal Vidyalaya"],["Priya Sahu","Study Managing Director"],["Preeti Sahu","HOD of Bal Vidyalaya"]] as const;
