export const courses=[
 ["Domestic Data Entry Operator","360 hours","English","IT/ITES","9th to 10th","₹25,000","Available"],["Sewing Machine Operator · AMH/Q0301","—","—","Apparel","—","—","—"],["Tailoring Course for Beginners","14:40 hours","English","Textiles","Any","₹25,000","Not available"],["Field Technician – Computers & Peripherals","10:20 hours","English","Electronics","—","₹5,000","Available"],["Advance Diploma in Computer Application","360 hours","English","IT/ITES","10th to Graduate","₹25,000","Available"],["CorelDRAW 2022 Essential Training","200 hours","English","IT/ITES","Any","₹25,000","Not available"],["AutoCAD Essentials for Civil Engineer","31:00 hours","English","IT/ITES","Graduate","₹5,000","Not available"],["Web Design & Development","3:39 hours","English","IT/ITES","Graduate","₹25,000","Not available"],["Mobile Repairing","On enquiry","—","—","—","—","—"],["Automotive Service Technician","On enquiry","—","—","—","—","—"],["Introduction to Automobiles","On enquiry","—","—","—","—","—"],["Solar Panel Installation Technician","On enquiry","—","—","—","—","—"]
] as const;
export const placements=[
 ["Wiring Harness Assemble Operator","Yazaki India Pvt. Ltd.","Bangalore","Apprenticeship","150","₹17,000–₹18,500"],["Assembly Line Operator","Tata Electronics Pvt. Ltd.","Bangalore","Full time","100","₹19,618–₹24,327"],["Electronic Hardware Design Engineer","Satyam Software Solutions Pvt. Ltd.","Noida","Full time","50","₹16,000–₹25,000"],["Assembly / Testing Operator","Hon Hai Technology Group (Foxconn)","Bangalore","Full time","300","₹17,000–₹25,000"],["Laptop Assembly Technician","Dixcon Technology Pedget","Bangalore","Full time","200","₹16,500–₹19,200"],["Wiring DRE-2 Technician","Stellantis Engineering India Pvt. Ltd.","Bangalore","Full time","90","₹17,600–₹26,200"]
] as const;
export const schemes={
 "pmgdisha":{name:"PMGDISHA",year:"2020–21",trainees:"300",agency:"CSC Governance Services India Ltd",summary:"Digital literacy for rural citizens, including marginalised communities and differently-abled persons.",detail:"Pradhan Mantri Gramin Digital Saksharta Abhiyaan supports citizens in rural areas to operate computers or digital access devices, communicate by email, browse the internet, access government services, search information and undertake digital payments."},
 "pmkvy-rpl":{name:"PMKVY / RPL",year:"2020–21",trainees:"50",agency:"CSC Governance Services India Ltd",summary:"Recognition of Prior Learning for people with existing skills.",detail:"RPL is a PMKVY skill-certification component that enables Indian youth with prior learning experience or skills to be assessed and certified, helping them secure a better livelihood."},
 "nsdc-paid-segment":{name:"NSDC Paid Segment",year:"2020–26",trainees:"600",agency:"IT&ITS SSC",summary:"Skill development through a public-private partnership model.",detail:"NSDC supports private sector initiatives for skill development through PPP models and functions under the Ministry of Skill Development & Entrepreneurship."},
 "sipda":{name:"SIPDA",year:"2021–22",trainees:"150 PwDs",agency:"DEPWD",summary:"Barrier-free access and skill support for Persons with Disabilities.",detail:"The scheme supports a barrier-free environment in institutions and public buildings, including access features such as ramps, rails, adapted toilets, braille signages and tactile flooring."},
 "csr-projects":{name:"CSR Projects",year:"2021–22",trainees:"67 PwDs",agency:"EFFICOR",summary:"Accenture Learning Exchange professional, digital and employability modules.",detail:"Under Leonard Cheshire, learners access modules in adaptability, communication, customer service, problem solving, teamwork, digital literacy, career planning, financial literacy and computer skills."},
 "cemca-ofc":{name:"CEMCA OFC Women’s & PWD Course",year:"2021–22",trainees:"50 PwDs + 100 women",agency:"ELECTRONIC SSC",summary:"Online certification in Optical Fiber Splicer training.",detail:"CEMCA collaborated with CSC e-Governance Services India Limited for online skill development and certification of Divyangjans and women in Optical Fiber Splicer courses."},
 "future-workspace":{name:"Future Workspace Skills Training",year:"2022–23",trainees:"956 PwDs",agency:"AIF",summary:"Career mentoring and market-aligned training for PwD students.",detail:"The American India Foundation project provides career mentoring, online skilling, market-aligned employability training and an entrepreneurial mindset. Completion includes certification from NSDC and the University of Mumbai."},
 "osda":{name:"OSDA Placement Link Training",year:"2023–26",trainees:"500 + 30 PwDs",agency:"OSDA",summary:"Placement-linked skill training for inclusive growth.",detail:"OSDA Odisha represents a commitment to inclusive growth through skill development, connecting modern technologies and traditional sectors for a dynamic and sustainable future."},
 "nabskill":{name:"NABARD / NABSKILL",year:"2023–24 & 2025–26",trainees:"60 + 60 SHI candidates",agency:"NABARD",summary:"Off-farm sector stakeholder and initiative interface.",detail:"NABSKILL is NABARD’s digital interface for capturing stakeholders and off-farm sector initiatives. NABARD’s mandate includes rural prosperity through credit and non-credit initiatives."},
 "pmdaksh":{name:"PMDAKSH",year:"2025–26",trainees:"60 SHI candidates",agency:"DEPWD",summary:"Training for PwDs towards wage or self-employment.",detail:"Under the National Action Plan for Skill Development of Persons with Disabilities, PwD skill training supports self-reliance, gainful wage or self-employment and mainstream societal inclusion."}
} as const;
export const schemeList=Object.entries(schemes);
export const team=[["Bibhuti Bhusan Swain","President"],["Bikash Kumar Swain","Secretary"],["Madhusmita Pradhan","Treasurer"],["Bikash Chandra Muni","State Head"],["Kesab Kumar Dakua","Placements Officer"],["Goutam Pradhan","Principal of Bal Vidyalaya"],["Priya Sahu","Study Managing Director"],["Preeti Sahu","HOD of Bal Vidyalaya"]] as const;
