"use client";
import Link from "next/link";
import { useState } from "react";
const links=[["About Us","/about"],["Our Work","/our-work"],["Schemes","/schemes"],["Student Corner","/student-corner"],["Bal Vidyalaya","/bal-vidyalaya"],["Training Centers","/training-centers"],["Placement","/placement"],["Contact Us","/contact"]];
export function Placeholder({label="PHOTO PLACEHOLDER"}:{label?:string}){return <div className="placeholder" role="img" aria-label={label}><b>✦</b><strong>{label}</strong><small>REPLACE WITH APPROVED ASSET</small></div>}
export function Navbar(){const [open,setOpen]=useState(false);return <><div className="topbar">Approved Training Partner of Skill India <span>t2tskills@gmail.com · +91 94376 61164</span></div><header className="nav"><Link href="/" className="brand"><i>T<em>2</em></i><b>T2T Skill Foundation<small>Skill development · Odisha</small></b></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>☰</button><nav className={open?"nav-open":""}>{links.map(([n,h])=><Link onClick={()=>setOpen(false)} href={h} key={h}>{n}</Link>)}</nav><Link href="/student-corner" className="btn small">Apply now →</Link></header></>}
export function Footer(){return <footer><div className="footer-grid"><div className="foot-brand"><i>T<em>2</em></i><h2>T2T Skill<br/>Foundation</h2></div><div><p>Training centre</p><span>Sheragada, Ganjam,<br/>Odisha – 761106</span></div><div><p>Contact</p><a href="tel:+919437661164">+91-9437661164</a><a href="mailto:t2tskills@gmail.com">t2tskills@gmail.com</a></div><div><p>Hours</p><span>Mon–Sat · 10:00 AM–07:00 PM<br/>Sunday · Closed</span></div></div><div className="footer-bottom">© {new Date().getFullYear()} T2T Skill Foundation <Link href="/">Back to top ↑</Link></div></footer>}
export function PageHero({eyebrow,title,copy}:{eyebrow:string,title:string,copy:string}){return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div><Placeholder/></section>}
export function Breadcrumb({current}:{current:string}){return <div className="crumb"><Link href="/">Home</Link><span>/</span><b>{current}</b></div>}
