"use client";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
const links=[["About Us","/about"],["Our Work","/our-work"],["Schemes","/schemes"],["Student Corner","/student-corner"],["Bal Vidyalaya","/bal-vidyalaya"],["Training Centers","/training-centers"],["Placement","/placement"],["Contact Us","/contact"]];
export function Placeholder({label="PHOTO PLACEHOLDER"}:{label?:string}){return <div className="placeholder" role="img" aria-label={label}><b>✦</b><strong>{label}</strong><small>REPLACE WITH APPROVED ASSET</small></div>}
export function Navbar(){const [open,setOpen]=useState(false);return <><div className="topbar">Approved Training Partner of Skill India <span>t2tskills@gmail.com · +91 94376 61164</span></div><header className="nav"><Link href="/" className="brand"><Image className="brand-logo" src="/logo.jpg" alt="T2T Skill Foundation" width={224} height={188} priority/><b>T2T Skill Foundation<small>Skill development · Odisha</small></b></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>☰</button><nav className={open?"nav-open":""}>{links.map(([n,h])=><Link onClick={()=>setOpen(false)} href={h} key={h}>{n}</Link>)}</nav><Link href="/student-corner" className="btn small">Apply now →</Link></header></>}
export function Footer(){return <footer><div className="footer-grid"><div className="foot-brand"><Image className="footer-logo" src="/logo.jpg" alt="T2T Skill Foundation" width={224} height={188}/><h2>T2T Skill<br/>Foundation</h2></div><div><p>Training centre</p><span>Sheragada, Ganjam,<br/>Odisha – 761106</span></div><div><p>Contact</p><a href="tel:+919437661164">+91-9437661164</a><a href="mailto:t2tskills@gmail.com">t2tskills@gmail.com</a></div><div><p>Hours</p><span>Mon–Sat · 10:00 AM–07:00 PM<br/>Sunday · Closed</span></div></div><div className="footer-bottom">© {new Date().getFullYear()} T2T Skill Foundation <Link href="/">Back to top ↑</Link></div></footer>}
export function PageHero({eyebrow,title,copy,imageSrc,imageAlt,imageBelow=false,imageOverlay=false}:{eyebrow:string,title:string,copy:string,imageSrc?:string,imageAlt?:string,imageBelow?:boolean,imageOverlay?:boolean}){const mediaStyle={width:"100%",height:"100%",objectFit:"cover" as const,display:"block"};return <section className={`page-hero${imageBelow?" page-hero--image-below":""}${imageOverlay?" page-hero--image-overlay":""}`}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{imageSrc?<div className="page-hero-image" aria-label={imageAlt ?? title}><img src={imageSrc} alt={imageAlt ?? title} style={mediaStyle} /></div>:<Placeholder/>}</section>}
/** Breadcrumbs intentionally omitted so each page starts directly below the header. */
export function Breadcrumb({current}:{current:string}){void current;return null}
