import Image from "next/image";
import { notFound } from "next/navigation";
import { Footer, Navbar, PageHero } from "../../components/site";
import { courses, placements } from "../../components/data";

const stories = [["Bigyani Pradhan", "/success/BIGYANI PRADHAN.jpg"], ["Nabin Behera", "/success/NABIN BEHERA.jpg"], ["Santoshini Pradhan", "/success/SANOSHINI PRADHAN.jpg"], ["Sibananda Behera", "/success/SIBANANDA BEHERA.jpg"], ["Vicky Sahu", "/success/VICKY SAHU.jpg"], ["Krishna Swain", "/success/krishna swain.jpg"]] as const;
const courseImages: Record<string, { src: string; alt: string }> = {
  "Domestic Data Entry Operator": { src: "/folderforuse/Domestic-Data-Entry-1.jpg", alt: "Domestic data entry training" },
  "Sewing Machine Operator · AMH/Q0301": { src: "/folderforuse/sewing-machine-operator-course-500x500.webp", alt: "Sewing machine operator at work" },
  "Tailoring Course for Beginners": { src: "/folderforuse/images.jpeg", alt: "Tailoring and sewing work" },
  "Field Technician – Computers & Peripherals": { src: "/folderforuse/desktop-repair-1.webp", alt: "Desktop computer repair work" },
  "Advance Diploma in Computer Application": { src: "/folderforuse/210222071953.jpg", alt: "Computer application course" },
  "CorelDRAW 2022 Essential Training": { src: "/folderforuse/advance-coreldraw-training-in-borivali-mumbai.webp", alt: "CorelDRAW design training" },
  "AutoCAD Essentials for Civil Engineer": { src: "/folderforuse/courseCovers_9135ad8bfe51_1780145782318.jpg", alt: "Civil design and AutoCAD planning" },
  "Web Design & Development": { src: "/folderforuse/Complete-Guide-to-Web-Development-and-Design.jpg", alt: "Web design and development" },
  "Mobile Repairing": { src: "/folderforuse/mobile-repairing-technician.png", alt: "Mobile repairing technician" },
  "Automotive Service Technician": { src: "/folderforuse/mechanic-and-vehicle-technician.jpg", alt: "Automotive service technician" },
  "Introduction to Automobiles": { src: "/folderforuse/automotive-technician.png", alt: "Automotive technician at work" },
  "Solar Panel Installation Technician": { src: "/folderforuse/23aa.jpg", alt: "Solar panel installation training" },
};

export default async function WorkSection({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  if (!['training', 'placements', 'success-stories', 'achievements'].includes(section)) notFound();
  const page = section === 'training' ? { eyebrow: 'Training', title: 'Skills for the work ahead.', copy: 'Professional learning across digital, technical, apparel and automotive skills.' } : section === 'placements' ? { eyebrow: 'Placements', title: 'Training that leads somewhere.', copy: 'Current opportunities and support for the next step after training.' } : section === 'success-stories' ? { eyebrow: 'Success stories', title: 'Transforming lives, one skill at a time.', copy: 'Discover inspiring stories of learners who opened new opportunities through training.' } : { eyebrow: 'Achievements', title: 'Progress you can see.', copy: 'A record of learning, inclusion and employment opportunity in Odisha.' };
  const heroImage = section === 'training' ? "/folderforuse/List 3 skills that you are grateful you have!.jpeg" : section === 'success-stories' ? "/folderforuse/Business Turnaround Strategy_ 7 Steps to Revive Business.jpeg" : section === 'placements' ? "/folderforuse/Achieving Goals with Strategic Planning, Target Arrow, Progress to Success.jpeg" : "/about/Classroom studying student child_  _ premium image by rawpixel.com _ audi";
  return <><Navbar /><main><div className="subpage-hero"><PageHero {...page} imageSrc={heroImage} imageAlt={`${page.eyebrow} at T2T Skill Foundation`} imageOverlay /></div>
    {section === 'training' && <section className="section programmes-section"><div className="programme-summary"><div><b>{courses.length}</b><span>programmes available</span></div><div><b>4</b><span>skill sectors represented</span></div><div><b>NSDC</b><span>certification status shown</span></div></div><div className="course-grid course-grid--detailed">{courses.map(([name, duration, language, sector, eligibility, price, cert]) => <article className="course" key={name}><div className="course-image"><Image src={courseImages[name].src} alt={courseImages[name].alt} width={640} height={360} sizes="(max-width: 600px) 100vw, (max-width: 900px) 50vw, 33vw" /></div><div className="course-topline"><span>{sector === '—' ? 'Skill training' : sector}</span><b>{cert}</b></div><h3>{name}</h3><dl><div><dt>Duration</dt><dd>{duration}</dd></div><div><dt>Language</dt><dd>{language}</dd></div><div><dt>Eligibility</dt><dd>{eligibility}</dd></div><div><dt>Course fee</dt><dd>{price}</dd></div></dl></article>)}</div></section>}
    {section === 'placements' && <section className="work-placements"><div className="section work-placements-inner"><div className="work-placement-summary"><b>890</b><span>current vacancies across six employer opportunities</span><a href="tel:+919437661164">Talk to our placement team →</a></div><div className="work-placement-list">{placements.map(([role, company, location, type, vacancies, salary]) => <article key={role}><div><span>{company}</span><h3>{role}</h3></div><dl><div><dt>Location</dt><dd>{location}</dd></div><div><dt>Role type</dt><dd>{type}</dd></div><div><dt>Vacancies</dt><dd>{vacancies}</dd></div><div><dt>Salary</dt><dd>{salary}</dd></div></dl></article>)}</div></div></section>}
    {section === 'success-stories' && <section className="section work-outcomes"><div className="success-story-grid">{stories.map(([name, src], index) => <figure className="success-story-card" key={src}><div className="success-story-image"><Image src={src} alt={`${name}, T2T Skill Foundation learner`} fill sizes="(max-width: 600px) 100vw, 50vw" quality={88} /></div><figcaption><span>Success story {String(index + 1).padStart(2, '0')}</span><b>{name}</b></figcaption></figure>)}</div></section>}
    {section === 'achievements' && <section className="work-achievements"><div className="section work-achievements-inner"><div><p className="eyebrow">Achievements</p><h2>Progress you can see.</h2></div><div className="work-achievements-content"><div className="work-achievement-gallery"><figure className="work-achievement-image"><Image src="/dhenkanala_1.jpg" alt="T2T Skill Foundation achievement programme" fill sizes="(max-width: 600px) 86vw, 42vw" /></figure><figure className="work-achievement-image"><Image src="/JOB FAIR.jpg.jpeg" alt="T2T Skill Foundation job fair" fill sizes="(max-width: 600px) 86vw, 42vw" /></figure></div><div className="work-achievement-stats"><article><b>2019</b><span>established in Odisha</span></article><article><b>890</b><span>current vacancies available</span></article><article><b>PwD</b><span>inclusive training focus</span></article></div></div></div></section>}
  </main><Footer /></>;
}
