import Image from "next/image";
import { Footer, Navbar } from "../components/site";
import { BalGalleryCarousel } from "../components/bal-gallery-carousel";
import { BalNews } from "../components/bal-news";

const photos = [
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.54.42 PM (1).jpeg", alt: "Educators performing a tricolour dance at the Independence Day programme", label: "Tricolour on the floor" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.54.41 PM (2).jpeg", alt: "Staff dancing in a line before the Happy Independence Day banner", label: "A school in celebration" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.54.56 PM.jpeg", alt: "Children dancing on stage at Annual Function Celebrations 2025", label: "Annual Function on stage" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.55.04 PM (1).jpeg", alt: "Independence Day flag hoisting with rangoli on the terrace", label: "Independence Day" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.55.17 PM.jpeg", alt: "Children lined up outdoors in house-colour uniforms", label: "House colours on parade" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.41.26 PM.jpeg", alt: "Children standing together for morning prayer", label: "A shared beginning" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.54.34 PM.jpeg", alt: "Children taking part in an outdoor school activity", label: "Play in the courtyard" },
  { src: "/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.42.00 PM.jpeg", alt: "Children in traditional costume at a cultural programme", label: "Festival on the mats" },
];

export default function BalVidyalaya() {
  return <><Navbar /><main className="bal-page">
    <section className="bal-hero"><Image src="/balvidyalay/IMG-20250731-WA0061.jpg" alt="Bal Vidyalaya children taking part in an interactive classroom activity" fill priority quality={90} sizes="100vw" /><div className="bal-hero-shade" /><div className="bal-hero-content"><p className="eyebrow">Bal Vidyalaya School · Sheragada</p><h1>Small hands.<br /><em>Bright futures.</em></h1><p>A joyful early-learning space where children explore, create and grow with confidence.</p><a className="bal-hero-link" href="#our-story">Discover our approach <span>↓</span></a></div><div className="bal-hero-tag"><span>Learning happens everywhere</span><b>Play · Explore · Discover</b></div></section>
    <section className="section bal-intro" id="our-story"><div><p className="eyebrow">A place to belong</p><h2>A happy beginning to a lifelong love of learning.</h2></div><div className="bal-intro-copy"><p>Bal Vidyalaya School, Sheragada brings early childhood education to life through active, child-centred learning. Every day gives children new ways to ask questions, express themselves and learn together.</p><p>Developed by T2T Skill Foundation in association with IIT Delhi, the programme aligns with NEP 2020 and supports age-appropriate learning through engaging activities, discovery and care.</p><div className="bal-intro-signoff"><span>Our promise</span><b>Every child is seen, heard and encouraged.</b></div><Image className="bal-programme-mark" src="/bal.jpeg" alt="Bal Vidyalaya — Technology Enabled Playful Learning" width={1536} height={588} sizes="(max-width: 900px) 260px, 300px" quality={90} /></div></section>
    <section className="bal-principles"><div className="section"><p className="eyebrow">Our learning world</p><div className="bal-principles-heading"><h2>Built around children and their wonder.</h2><p>We make room for play, friendship, movement and meaningful discovery in every learning experience.</p></div><div className="bal-principles-grid"><article><span>01</span><h3>Learn by doing</h3><p>Hands-on activities make ideas memorable and help children build skills naturally.</p></article><article><span>02</span><h3>Grow with confidence</h3><p>Encouragement and care help every child find their voice and feel proud to participate.</p></article><article><span>03</span><h3>Discover together</h3><p>Shared play and guided exploration nurture curiosity, kindness and connection.</p></article></div></div></section>
    <section className="section bal-gallery-section"><div className="bal-gallery-heading"><div><p className="eyebrow">Life at Bal Vidyalaya</p><h2>Little moments. Big learning.</h2></div><p>From creative classroom activities to proud celebrations, these are the moments that make our school feel like home.</p></div><BalGalleryCarousel photos={photos} /></section>
    <BalNews />
    <section className="bal-closing"><div className="bal-closing-image"><Image src="/balvidyalay/activity/WhatsApp Image 2026-09-03 at 4.55.16 PM (1).jpeg" alt="Children with certificates of competition, trophies and flags at Bal Vidyalaya" width={1280} height={960} sizes="(max-width: 900px) 100vw, 50vw" quality={90} /></div><div className="bal-closing-copy"><p className="eyebrow">Every day matters</p><h2>Here, every milestone is worth celebrating.</h2><p>We celebrate curiosity, courage and the small steps that help children become confident learners.</p><a href="/contact" className="btn">Talk to our team →</a></div></section>
  </main><Footer /></>;
}
